// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLHK_Webapp.Models;

#nullable disable

namespace QLHK_Webapp.Migrations
{
    [DbContext(typeof(DangKyKhamDbContext))]
    [Migration("20250214073440_update_key_nguoidung_thongtinhk")]
    partial class update_key_nguoidung_thongtinhk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QLHK_Webapp.Models.LoaiKham", b =>
                {
                    b.Property<Guid>("LoaiKhamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenLoaiKham")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LoaiKhamID");

                    b.ToTable("LoaiKham", (string)null);

                    b.HasData(
                        new
                        {
                            LoaiKhamID = new Guid("ab5d63af-f747-46ba-8e09-f81517402852"),
                            TenLoaiKham = "Khám tổng quát"
                        },
                        new
                        {
                            LoaiKhamID = new Guid("01de28b9-4c60-4e32-b778-e9601c903a09"),
                            TenLoaiKham = "Khám chuyên khoa"
                        },
                        new
                        {
                            LoaiKhamID = new Guid("55d1015c-8b4f-4836-a383-8e7d7713a870"),
                            TenLoaiKham = "Khám nội"
                        },
                        new
                        {
                            LoaiKhamID = new Guid("f245fe01-8051-40b5-b964-f680a2e2a6be"),
                            TenLoaiKham = "Khám ngoại"
                        },
                        new
                        {
                            LoaiKhamID = new Guid("0295f7b6-e1f2-4280-a75d-71d81bc95b26"),
                            TenLoaiKham = "Khám sản"
                        },
                        new
                        {
                            LoaiKhamID = new Guid("8ce53862-5b2a-437d-a1e4-3e809b4aca23"),
                            TenLoaiKham = "Khám nhi"
                        });
                });

            modelBuilder.Entity("QLHK_Webapp.Models.NguoiDung", b =>
                {
                    b.Property<Guid>("NguoiDungID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("NguoiDungID");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("QLHK_Webapp.Models.PhongKham", b =>
                {
                    b.Property<Guid>("PhongKhamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenPhongKham")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PhongKhamID");

                    b.ToTable("PhongKham", (string)null);

                    b.HasData(
                        new
                        {
                            PhongKhamID = new Guid("d96fb04d-b207-4e49-972b-255222a83f57"),
                            TenPhongKham = "Phòng khám 1"
                        },
                        new
                        {
                            PhongKhamID = new Guid("e3f1bf20-87fe-48f8-b5d3-e089b98cf730"),
                            TenPhongKham = "Phòng khám 2"
                        },
                        new
                        {
                            PhongKhamID = new Guid("fa9e6f4b-a6ea-4af9-9714-e4eb6c5b64d9"),
                            TenPhongKham = "Phòng khám 3"
                        },
                        new
                        {
                            PhongKhamID = new Guid("c3b11d8c-207a-4062-a745-c05f16d20c9f"),
                            TenPhongKham = "Phòng khám 4"
                        },
                        new
                        {
                            PhongKhamID = new Guid("cfa33b60-bb94-4890-b98e-3aa33d4b8b81"),
                            TenPhongKham = "Phòng khám 5"
                        });
                });

            modelBuilder.Entity("QLHK_Webapp.Models.ThongTinHenKham", b =>
                {
                    b.Property<Guid>("ThongTinHenKhamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("LoaiKhamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LyDoKham")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("NgayHenKham")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NguoiDungID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhongKhamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ThongTinHenKhamID");

                    b.HasIndex("LoaiKhamID");

                    b.HasIndex("NguoiDungID");

                    b.HasIndex("PhongKhamID");

                    b.ToTable("ThongTinHenKham", (string)null);
                });

            modelBuilder.Entity("QLHK_Webapp.Models.ThongTinHenKham", b =>
                {
                    b.HasOne("QLHK_Webapp.Models.LoaiKham", "LoaiKham")
                        .WithMany()
                        .HasForeignKey("LoaiKhamID");

                    b.HasOne("QLHK_Webapp.Models.NguoiDung", "NguoiDung")
                        .WithMany("ThongTinHenKhams")
                        .HasForeignKey("NguoiDungID");

                    b.HasOne("QLHK_Webapp.Models.PhongKham", "PhongKham")
                        .WithMany()
                        .HasForeignKey("PhongKhamID");

                    b.Navigation("LoaiKham");

                    b.Navigation("NguoiDung");

                    b.Navigation("PhongKham");
                });

            modelBuilder.Entity("QLHK_Webapp.Models.NguoiDung", b =>
                {
                    b.Navigation("ThongTinHenKhams");
                });
#pragma warning restore 612, 618
        }
    }
}
