// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLHK_Webapp.Models;

#nullable disable

namespace QLHK_Webapp.Migrations
{
    [DbContext(typeof(DangKyKhamDbContext))]
    [Migration("20250214072953_ThemCot_TrangThai_ThongTinHenKham")]
    partial class ThemCot_TrangThai_ThongTinHenKham
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QLHK_Webapp.Models.LoaiKham", b =>
                {
                    b.Property<Guid>("LoaiKhamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenLoaiKham")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LoaiKhamID");

                    b.ToTable("LoaiKham", (string)null);

                    b.HasData(
                        new
                        {
                            LoaiKhamID = new Guid("b798975f-2980-491c-b63f-181c4cc439bc"),
                            TenLoaiKham = "Khám tổng quát"
                        },
                        new
                        {
                            LoaiKhamID = new Guid("35c60cc6-4e4c-464f-8a8d-c00513e6edb2"),
                            TenLoaiKham = "Khám chuyên khoa"
                        },
                        new
                        {
                            LoaiKhamID = new Guid("bb86bd6b-1231-48cb-98e8-d5579623d6c1"),
                            TenLoaiKham = "Khám nội"
                        },
                        new
                        {
                            LoaiKhamID = new Guid("e4943923-95f5-4efa-9c7c-24d2174cf68e"),
                            TenLoaiKham = "Khám ngoại"
                        },
                        new
                        {
                            LoaiKhamID = new Guid("cd7b8bb1-467a-4de9-a983-cb1ed1090ac1"),
                            TenLoaiKham = "Khám sản"
                        },
                        new
                        {
                            LoaiKhamID = new Guid("8f8b6667-8bb5-404d-89ce-ce065d29987d"),
                            TenLoaiKham = "Khám nhi"
                        });
                });

            modelBuilder.Entity("QLHK_Webapp.Models.NguoiDung", b =>
                {
                    b.Property<Guid>("NguoiDungID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("NguoiDungID");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("QLHK_Webapp.Models.PhongKham", b =>
                {
                    b.Property<Guid>("PhongKhamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenPhongKham")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PhongKhamID");

                    b.ToTable("PhongKham", (string)null);

                    b.HasData(
                        new
                        {
                            PhongKhamID = new Guid("73bb3420-9a44-408e-9bcb-19f45114c0a0"),
                            TenPhongKham = "Phòng khám 1"
                        },
                        new
                        {
                            PhongKhamID = new Guid("edd30b1c-c233-4a97-b359-a68bd7ac3864"),
                            TenPhongKham = "Phòng khám 2"
                        },
                        new
                        {
                            PhongKhamID = new Guid("50ca55f1-3523-45cc-84e0-9769bcf5ea5f"),
                            TenPhongKham = "Phòng khám 3"
                        },
                        new
                        {
                            PhongKhamID = new Guid("e39b27d6-127b-446b-8458-c70e485ec2ec"),
                            TenPhongKham = "Phòng khám 4"
                        },
                        new
                        {
                            PhongKhamID = new Guid("fbd97991-4a00-4e80-9fe7-5a01c75823c4"),
                            TenPhongKham = "Phòng khám 5"
                        });
                });

            modelBuilder.Entity("QLHK_Webapp.Models.ThongTinHenKham", b =>
                {
                    b.Property<Guid>("ThongTinHenKhamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("LoaiKhamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LyDoKham")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("NgayHenKham")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NguoiDungID")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhongKhamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ThongTinHenKhamID");

                    b.HasIndex("LoaiKhamID");

                    b.HasIndex("NguoiDungID");

                    b.HasIndex("PhongKhamID");

                    b.ToTable("ThongTinHenKham", (string)null);
                });

            modelBuilder.Entity("QLHK_Webapp.Models.ThongTinHenKham", b =>
                {
                    b.HasOne("QLHK_Webapp.Models.LoaiKham", "LoaiKham")
                        .WithMany()
                        .HasForeignKey("LoaiKhamID");

                    b.HasOne("QLHK_Webapp.Models.NguoiDung", "NguoiDung")
                        .WithMany("ThongTinHenKhams")
                        .HasForeignKey("NguoiDungID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLHK_Webapp.Models.PhongKham", "PhongKham")
                        .WithMany()
                        .HasForeignKey("PhongKhamID");

                    b.Navigation("LoaiKham");

                    b.Navigation("NguoiDung");

                    b.Navigation("PhongKham");
                });

            modelBuilder.Entity("QLHK_Webapp.Models.NguoiDung", b =>
                {
                    b.Navigation("ThongTinHenKhams");
                });
#pragma warning restore 612, 618
        }
    }
}
