// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLHK_Webapp.Models;

#nullable disable

namespace QLHK_Webapp.Migrations
{
    [DbContext(typeof(DangKyKhamDbContext))]
    partial class DangKyKhamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QLHK_Webapp.Models.LoaiKham", b =>
                {
                    b.Property<Guid>("LoaiKhamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenLoaiKham")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LoaiKhamID");

                    b.ToTable("LoaiKham", (string)null);

                    b.HasData(
                        new
                        {
                            LoaiKhamID = new Guid("d35b3a72-9024-4721-bacb-f95315405e3c"),
                            TenLoaiKham = "Khám tổng quát"
                        },
                        new
                        {
                            LoaiKhamID = new Guid("79578e72-132e-4d10-9454-92c87cb57fec"),
                            TenLoaiKham = "Khám chuyên khoa"
                        },
                        new
                        {
                            LoaiKhamID = new Guid("d18dca48-2b95-4ecf-a27b-e76ec2174206"),
                            TenLoaiKham = "Khám nội"
                        },
                        new
                        {
                            LoaiKhamID = new Guid("11e84f0b-456f-4862-aa7e-b71860797235"),
                            TenLoaiKham = "Khám ngoại"
                        },
                        new
                        {
                            LoaiKhamID = new Guid("b9eb68f1-3795-417d-9010-dd580d5c41f6"),
                            TenLoaiKham = "Khám sản"
                        },
                        new
                        {
                            LoaiKhamID = new Guid("3095d451-a6a4-4050-ba51-5ad1ec722ecc"),
                            TenLoaiKham = "Khám nhi"
                        });
                });

            modelBuilder.Entity("QLHK_Webapp.Models.NguoiDung", b =>
                {
                    b.Property<Guid>("NguoiDungID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("NguoiDungID");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("QLHK_Webapp.Models.PhongKham", b =>
                {
                    b.Property<Guid>("PhongKhamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenPhongKham")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PhongKhamID");

                    b.ToTable("PhongKham", (string)null);

                    b.HasData(
                        new
                        {
                            PhongKhamID = new Guid("e320ce8f-8fd7-4aae-95d2-54b2be87ae0d"),
                            TenPhongKham = "Phòng khám 1"
                        },
                        new
                        {
                            PhongKhamID = new Guid("70e80be9-7302-44e9-9d50-78ffba9d2e21"),
                            TenPhongKham = "Phòng khám 2"
                        },
                        new
                        {
                            PhongKhamID = new Guid("16051c25-9886-44ce-b495-b415f5ecf07c"),
                            TenPhongKham = "Phòng khám 3"
                        },
                        new
                        {
                            PhongKhamID = new Guid("319c86e3-036e-41db-9458-fb5323932442"),
                            TenPhongKham = "Phòng khám 4"
                        },
                        new
                        {
                            PhongKhamID = new Guid("70ab970c-f075-4048-879e-7a403ede0e58"),
                            TenPhongKham = "Phòng khám 5"
                        });
                });

            modelBuilder.Entity("QLHK_Webapp.Models.ThongTinHenKham", b =>
                {
                    b.Property<Guid>("ThongTinHenKhamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("LoaiKhamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LyDoKham")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("NgayHenKham")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NguoiDungID")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhongKhamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ThongTinHenKhamID");

                    b.HasIndex("LoaiKhamID");

                    b.HasIndex("NguoiDungID");

                    b.HasIndex("PhongKhamID");

                    b.ToTable("ThongTinHenKham", (string)null);
                });

            modelBuilder.Entity("QLHK_Webapp.Models.ThongTinHenKham", b =>
                {
                    b.HasOne("QLHK_Webapp.Models.LoaiKham", "LoaiKham")
                        .WithMany()
                        .HasForeignKey("LoaiKhamID");

                    b.HasOne("QLHK_Webapp.Models.NguoiDung", "NguoiDung")
                        .WithMany("ThongTinHenKhams")
                        .HasForeignKey("NguoiDungID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLHK_Webapp.Models.PhongKham", "PhongKham")
                        .WithMany()
                        .HasForeignKey("PhongKhamID");

                    b.Navigation("LoaiKham");

                    b.Navigation("NguoiDung");

                    b.Navigation("PhongKham");
                });

            modelBuilder.Entity("QLHK_Webapp.Models.NguoiDung", b =>
                {
                    b.Navigation("ThongTinHenKhams");
                });
#pragma warning restore 612, 618
        }
    }
}
